//! Checkpoint singleton driver — state updates and membership queries.
//!
//! The checkpoint singleton is the canonical on-chain source of truth for
//! L2 state. It has two spend paths:
//!
//! ## Spend Path 1: Checkpoint (CHK-003, CHK-004)
//!
//! Advances the epoch. Requires Groth16 proof + BLS aggregate signature.
//! On success: epoch increments, state updates, announcement emitted.
//!
//! CLVM cost: ~17.2M units (0.157% of block limit).
//! See [spec-clvm-costs.md Lines 50-80](../../docs/resources/spec-clvm-costs.md).
//!
//! ## Spend Path 2: Membership Query (CHK-005, CHK-006)
//!
//! Verifies Merkle proof, emits membership/non-membership announcement.
//! Permissionless (no signature needed). State unchanged.
//! Used by registration coin for collateral recovery.
//!
//! CLVM cost: ~4.1M units (0.037% of block limit).
//!
//! ## Puzzle Artifacts
//!
//! | Artifact | Path | Generated By |
//! |----------|------|-------------|
//! | CLVM hex | `puzzles/compiled/checkpoint_inner.hex` | `rue build -x puzzles/checkpoint_inner.rue` |
//! | Mod hash | `puzzles/compiled/checkpoint_inner.hash` | `rue build --hash puzzles/checkpoint_inner.rue` |
//!
//! See [spec-checkpoint-singleton.md](../../docs/resources/spec-checkpoint-singleton.md)
//! for the full puzzle specification.
//! See [spec-consensus-crate.md Lines 1200-1274](../../docs/resources/spec-consensus-crate.md)
//! for the driver specification.

use chia_protocol::Bytes32;
use chia_protocol::SpendBundle;

use crate::error::ConsensusResult;
use crate::state::CheckpointSingletonState;

/// Compiled CLVM hex for the checkpoint inner puzzle.
///
/// This is the UNCURRIED inner puzzle. At deployment, it is curried with:
/// (INNER_MOD_HASH, VK, IC, TREE_DEPTH, EMPTY_LEAF_HASH, STATE)
///
/// The curried puzzle is wrapped by singleton_top_layer_v1_1.
/// STATE changes every checkpoint spend; all other params are immutable.
///
/// See [spec-checkpoint-singleton.md Lines 50-100](../../docs/resources/spec-checkpoint-singleton.md) —
/// Curried In Parameters.
pub const CHECKPOINT_INNER_PUZZLE_HEX: &str =
    include_str!("../../puzzles/compiled/checkpoint_inner.hex");

/// Tree hash of the uncurried checkpoint inner puzzle.
///
/// This is the MOD_HASH used for:
/// - Singleton morphing: inner puzzle outputs curry_tree_hash(MOD_HASH, args)
/// - Configuration: stored in NetworkConfig.checkpoint_inner_mod_hash
///
/// See [spec-checkpoint-singleton.md Lines 100-130](../../docs/resources/spec-checkpoint-singleton.md).
pub const CHECKPOINT_INNER_MOD_HASH_HEX: &str =
    include_str!("../../puzzles/compiled/checkpoint_inner.hash");

/// Spend the checkpoint singleton to advance the epoch (spend path 1).
///
/// Builds a spend bundle containing:
/// - Groth16 proof (192 bytes: A+B+C) verified via bls_pairing_identity
/// - BLS aggregate signature verified via bls_verify
/// - Pre-computed scalars for VK input linear combination
/// - New state values (state_root, merkle_root, validator_count)
///
/// The puzzle auto-increments epoch = old_epoch + 1 (CHK-009).
/// The checkpoint_message includes epoch, binding the proof to this specific epoch.
///
/// See [spec-consensus-crate.md Lines 1806-1900](../../docs/resources/spec-consensus-crate.md).
/// See [spec-checkpoint-singleton.md Lines 130-200](../../docs/resources/spec-checkpoint-singleton.md) —
/// Spend Path 1: Checkpoint.
pub fn spend_checkpoint_singleton(
    _current_state: &CheckpointSingletonState,
    _new_state_root: Bytes32,
    _proof: &[u8],
    _aggregate_signature: &[u8],
) -> ConsensusResult<SpendBundle> {
    // TODO: Implement using chia-wallet-sdk SpendContext
    // See build_chk_path_env() in tests/vv_req_chk_008.rs for CLVM env construction
    // See generate_proof() in prover/prove.rs for proof generation
    todo!()
}

/// Fetch the current checkpoint singleton state from the Chia node.
///
/// Queries by launcher_id to find the current unspent singleton,
/// then decurries the puzzle to extract STATE fields.
///
/// See [spec-indexer.md Lines 100-150](../../docs/resources/spec-indexer.md) —
/// Checkpoint State Updates.
pub fn fetch_checkpoint_singleton_state(
    _launcher_id: Bytes32,
) -> ConsensusResult<CheckpointSingletonState> {
    // TODO: Implement — needs FullNodeClient for RPC queries
    // Decurry the singleton inner puzzle to extract STATE struct
    todo!()
}

/// Query membership status via the checkpoint singleton (spend path 2).
///
/// Builds a permissionless spend bundle (no signature needed, CHK-006) that:
/// 1. Verifies a Merkle inclusion/exclusion proof against validator_merkle_root
/// 2. Emits a CreateCoinAnnouncement with membership/non-membership status
/// 3. Recreates the singleton UNCHANGED (same state, same puzzle hash)
///
/// The announcement is used by the registration coin for collateral recovery
/// (REG-004: ASSERT_COIN_ANNOUNCEMENT of the non-membership announcement).
///
/// See [spec-consensus-crate.md Lines 2076-2105](../../docs/resources/spec-consensus-crate.md).
/// See [spec-checkpoint-singleton.md Lines 200-280](../../docs/resources/spec-checkpoint-singleton.md) —
/// Spend Path 2: Membership Query.
pub fn spend_checkpoint_singleton_membership_query(
    _current_state: &CheckpointSingletonState,
    _pubkey: &[u8; 48],
) -> ConsensusResult<SpendBundle> {
    // TODO: Implement using chia-wallet-sdk SpendContext
    // See prepare_collateral_recovery() in validator/exit.rs for the off-chain setup
    todo!()
}
