//! Network coin singleton driver — builds spend bundles for registration.
//!
//! The network coin is the canonical registration authority for the L2 network.
//! Validators spend it to create their registration coin (NET-002, NET-003).
//! After each spend, it recreates itself for the next registration (NET-004).
//!
//! ## Puzzle Artifacts
//!
//! | Artifact | Path | Generated By |
//! |----------|------|-------------|
//! | CLVM hex | `puzzles/compiled/network_coin_inner.hex` | `rue build -x puzzles/network_coin_inner.rue` |
//! | Mod hash | `puzzles/compiled/network_coin_inner.hash` | `rue build --hash puzzles/network_coin_inner.rue` |
//!
//! ## Curried Parameters (fixed at deployment)
//!
//! | Parameter | Type | Description |
//! |-----------|------|-------------|
//! | `INNER_MOD_HASH` | Bytes32 | Tree hash of this module (for singleton morphing) |
//! | `registration_coin_mod_hash` | Bytes32 | Tree hash of uncurried registration coin puzzle |
//! | `collateral_amount` | Int | Required collateral per validator in mojos |
//! | `checkpoint_singleton_id` | Bytes32 | Launcher ID of the checkpoint singleton |
//!
//! See [spec-network-coin.md](../../docs/resources/spec-network-coin.md) for the full
//! puzzle specification.
//! See [spec-consensus-crate.md Lines 1026-1120](../../docs/resources/spec-consensus-crate.md)
//! for the driver code specification.

use chia_protocol::Bytes32;
use chia_protocol::SpendBundle;

use crate::config::NetworkConfig;
use crate::error::ConsensusResult;

/// Compiled CLVM hex for the network coin inner puzzle.
/// Generated by `rue build -x puzzles/network_coin_inner.rue`.
///
/// This is the UNCURRIED inner puzzle. At deployment, it is curried with
/// (INNER_MOD_HASH, registration_coin_mod_hash, collateral_amount, checkpoint_singleton_id).
/// The curried puzzle is then wrapped by singleton_top_layer_v1_1.
///
/// See [spec-network-coin.md Lines 30-60](../../docs/resources/spec-network-coin.md) —
/// Curried In Parameters.
pub const NETWORK_COIN_INNER_PUZZLE_HEX: &str =
    include_str!("../../puzzles/compiled/network_coin_inner.hex");

/// Tree hash of the uncurried network coin inner puzzle.
/// Generated by `rue build --hash puzzles/network_coin_inner.rue`.
///
/// This is the MOD_HASH used for:
/// - Singleton morphing: inner puzzle outputs this hash, wrapper transforms to full singleton hash
/// - Puzzle hash verification: indexer checks coins match expected hash
///
/// See [spec-network-coin.md Lines 60-80](../../docs/resources/spec-network-coin.md) —
/// Puzzle Hash.
pub const NETWORK_COIN_INNER_MOD_HASH_HEX: &str =
    include_str!("../../puzzles/compiled/network_coin_inner.hash");

/// Deploy a new network coin singleton from the genesis coin.
///
/// Creates the singleton launcher and first network coin in a single spend bundle.
/// Called during initial network deployment (DEP-002).
///
/// See [spec-consensus-crate.md Lines 1060-1090](../../docs/resources/spec-consensus-crate.md).
/// See [spec-deployment-runbook.md Lines 100-150](../../docs/resources/spec-deployment-runbook.md) — Step 4.
pub fn deploy_network_coin(_config: &NetworkConfig) -> ConsensusResult<SpendBundle> {
    // TODO: Implement using chia-wallet-sdk Launcher API
    // See deploy_both_singletons() in puzzles/deploy.rs for reference pattern
    todo!()
}

/// Register a validator by spending the network coin.
///
/// Builds a spend bundle that:
/// 1. Spends the current network coin singleton
/// 2. Creates a registration coin with `collateral_amount` (NET-003)
/// 3. Includes AGG_SIG_ME proving validator controls pubkey (NET-002)
/// 4. Adds pubkey as first memo on CREATE_COIN for indexer (NET-005)
/// 5. Recreates the network coin for the next registration (NET-004)
///
/// See [spec-consensus-crate.md Lines 1742-1790](../../docs/resources/spec-consensus-crate.md).
/// See [spec-network-coin.md Lines 100-200](../../docs/resources/spec-network-coin.md).
pub fn register_validator(
    _config: &NetworkConfig,
    _pubkey: &[u8; 48],
) -> ConsensusResult<SpendBundle> {
    // TODO: Implement using chia-wallet-sdk SpendContext
    // Needs: current network coin state (coin, lineage_proof) from sync()
    // See compute_registration_signing_message() in validator/registration.rs for the AGG_SIG_ME message
    todo!()
}

/// Fetch the current network coin state from the Chia node.
///
/// Queries by launcher_id to find the current unspent singleton coin.
///
/// See [spec-indexer.md Lines 50-100](../../docs/resources/spec-indexer.md) —
/// Network Coin State.
pub fn fetch_network_coin_state(_launcher_id: Bytes32) -> ConsensusResult<()> {
    // TODO: Implement — needs FullNodeClient for RPC queries
    todo!()
}
