//! Network coin singleton driver.
//!
//! NET-001: Inner puzzle loaded from compiled Rue artifact.
//!
//! The puzzle is authored in Rue (`puzzles/network_coin_inner.rue`), compiled
//! to CLVM hex (`puzzles/compiled/network_coin_inner.hex`), and embedded into
//! this driver at compile time via `include_str!`. The tree-hash
//! (`puzzles/compiled/network_coin_inner.hash`) identifies the inner puzzle
//! before singleton wrapping.
//!
//! See [spec-network-coin.md](../../docs/resources/spec-network-coin.md).

use chia_protocol::Bytes32;
use chia_protocol::SpendBundle;

use crate::config::NetworkConfig;
use crate::error::ConsensusResult;

/// Compiled CLVM hex for the network coin inner puzzle.
/// Generated by `rue build -x puzzles/network_coin_inner.rue`.
/// This is the uncurried inner puzzle — currying adds
/// registration_coin_mod_hash, collateral_amount, and checkpoint_singleton_id.
pub const NETWORK_COIN_INNER_PUZZLE_HEX: &str =
    include_str!("../../puzzles/compiled/network_coin_inner.hex");

/// Tree hash of the uncurried network coin inner puzzle.
/// Generated by `rue build --hash puzzles/network_coin_inner.rue`.
pub const NETWORK_COIN_INNER_MOD_HASH_HEX: &str =
    include_str!("../../puzzles/compiled/network_coin_inner.hash");

/// Deploy a new network coin singleton.
pub fn deploy_network_coin(_config: &NetworkConfig) -> ConsensusResult<SpendBundle> {
    // TODO: Implement using chia-wallet-sdk
    todo!()
}

/// Register a validator through the network coin.
pub fn register_validator(
    _config: &NetworkConfig,
    _pubkey: &[u8; 48],
) -> ConsensusResult<SpendBundle> {
    // TODO: Implement using chia-wallet-sdk
    todo!()
}

/// Fetch the current network coin state.
pub fn fetch_network_coin_state(_launcher_id: Bytes32) -> ConsensusResult<()> {
    // TODO: Implement
    todo!()
}
