//! Registration coin driver — collateral management and recovery.
//!
//! Each registration coin holds one validator's collateral. It is created
//! by spending the network coin (NET-003) and can only be spent when the
//! checkpoint singleton confirms the validator is no longer active (REG-003).
//!
//! ## Puzzle Artifacts
//!
//! | Artifact | Path | Generated By |
//! |----------|------|-------------|
//! | CLVM hex | `puzzles/compiled/registration_coin.hex` | `rue build -x puzzles/registration_coin.rue` |
//! | Mod hash | `puzzles/compiled/registration_coin.hash` | `rue build --hash puzzles/registration_coin.rue` |
//!
//! ## Curried Parameters (fixed at creation by network coin)
//!
//! | Parameter | Type | Description |
//! |-----------|------|-------------|
//! | `VALIDATOR_PUBKEY` | PublicKey (48 bytes) | The validator's BLS G1 key |
//! | `CHECKPOINT_SINGLETON_ID` | Bytes32 | Checkpoint singleton coin ID at registration time |
//!
//! ## Security Properties
//!
//! - Collateral locked until non-membership proof (REG-003, SEC-003)
//! - Epoch replay protection via announcement format (REG-006, SEC-006)
//! - Lineage verified by indexer, not on-chain (REG-002)
//!
//! See [spec-registration-coin.md](../../docs/resources/spec-registration-coin.md)
//! for the full puzzle specification.
//! See [spec-consensus-crate.md Lines 1120-1200](../../docs/resources/spec-consensus-crate.md)
//! for the driver specification.

use chia_protocol::Bytes32;
use chia_protocol::SpendBundle;

use crate::error::ConsensusResult;

/// Compiled CLVM hex for the registration coin puzzle.
/// Generated by `rue build -x puzzles/registration_coin.rue`.
///
/// This is the UNCURRIED puzzle. Each validator's registration coin is
/// curried with (VALIDATOR_PUBKEY, CHECKPOINT_SINGLETON_ID), producing
/// a unique puzzle hash per validator.
///
/// The puzzle has two conditions:
/// 1. ASSERT_COIN_ANNOUNCEMENT — non-membership proof (REG-004)
/// 2. CREATE_COIN — return collateral to destination (REG-005)
///
/// See [spec-registration-coin.md Lines 50-100](../../docs/resources/spec-registration-coin.md).
pub const REGISTRATION_COIN_PUZZLE_HEX: &str =
    include_str!("../../puzzles/compiled/registration_coin.hex");

/// Tree hash of the uncurried registration coin puzzle.
/// Generated by `rue build --hash puzzles/registration_coin.rue`.
///
/// This MOD_HASH is used by:
/// - Network coin: `curry_tree_hash(MOD_HASH, pubkey, checkpoint_id)` → registration puzzle hash
/// - Indexer: verify registration coins have correct puzzle hash (IDX-002)
///
/// See [spec-registration-coin.md Lines 100-130](../../docs/resources/spec-registration-coin.md) —
/// Computing the Registration Coin Puzzle Hash.
pub const REGISTRATION_COIN_MOD_HASH_HEX: &str =
    include_str!("../../puzzles/compiled/registration_coin.hash");

/// Spend a registration coin to recover collateral.
///
/// Builds a two-spend bundle:
/// 1. Checkpoint singleton membership query (emits non-membership announcement)
/// 2. Registration coin spend (asserts announcement, returns collateral)
///
/// Both spends must be in the same bundle (atomic).
///
/// See [spec-consensus-crate.md Lines 2011-2055](../../docs/resources/spec-consensus-crate.md).
/// See [spec-registration-coin.md Lines 200-280](../../docs/resources/spec-registration-coin.md) —
/// Full Collateral Recovery Spend Bundle.
pub fn spend_registration_coin(_coin_id: Bytes32) -> ConsensusResult<SpendBundle> {
    // TODO: Implement using chia-wallet-sdk SpendContext
    // See prepare_collateral_recovery() in validator/exit.rs for parameter computation
    // See build_chk_path_env() in tests/vv_req_chk_008.rs for CLVM env construction
    todo!()
}

/// Compute the registration coin puzzle hash for a specific validator.
///
/// Formula: `curry_tree_hash(REGISTRATION_COIN_MOD_HASH, [tree_hash(pubkey), tree_hash(checkpoint_id)])`
///
/// This must match the on-chain `curry_tree_hash` in network_coin_inner.rue (NET-003).
///
/// See [spec-registration-coin.md Lines 100-130](../../docs/resources/spec-registration-coin.md).
/// See `registration_coin_puzzle_hash()` in indexer/validator_set.rs for the indexer's version.
pub fn registration_coin_puzzle_hash(
    _checkpoint_singleton_id: Bytes32,
    _pubkey: &[u8; 48],
) -> Bytes32 {
    // TODO: Implement currying using clvm_utils::curry_tree_hash
    // Must match: indexer/validator_set.rs::registration_coin_puzzle_hash()
    Bytes32::default()
}
