//! Registration coin driver.
//!
//! REG-001: Puzzle structure — loaded from compiled Rue artifact.
//!
//! The puzzle is authored in Rue (`puzzles/registration_coin.rue`), compiled
//! to CLVM hex (`puzzles/compiled/registration_coin.hex`), and embedded into
//! this driver at compile time via `include_str!`. The tree-hash of the
//! compiled puzzle (`puzzles/compiled/registration_coin.hash`) is the
//! `REGISTRATION_COIN_MOD_HASH` used by the network coin to compute the
//! curried puzzle hash for each validator.
//!
//! See [spec-registration-coin.md](../../docs/resources/spec-registration-coin.md).

use chia_protocol::Bytes32;
use chia_protocol::SpendBundle;

use crate::error::ConsensusResult;

/// Compiled CLVM hex for the registration coin puzzle.
/// Generated by `rue build -x puzzles/registration_coin.rue`.
/// This is the uncurried puzzle — currying adds VALIDATOR_PUBKEY and
/// CHECKPOINT_SINGLETON_ID per REG-001.
pub const REGISTRATION_COIN_PUZZLE_HEX: &str =
    include_str!("../../puzzles/compiled/registration_coin.hex");

/// Tree hash of the uncurried registration coin puzzle.
/// Generated by `rue build --hash puzzles/registration_coin.rue`.
/// Used by the network coin to compute curried puzzle hashes (NET-003)
/// and by the indexer for lineage verification (IDX-002).
pub const REGISTRATION_COIN_MOD_HASH_HEX: &str =
    include_str!("../../puzzles/compiled/registration_coin.hash");

/// Spend a registration coin to recover collateral.
pub fn spend_registration_coin(_coin_id: Bytes32) -> ConsensusResult<SpendBundle> {
    // TODO: Implement using chia-wallet-sdk
    todo!()
}

/// Compute the registration coin puzzle hash.
pub fn registration_coin_puzzle_hash(
    _checkpoint_singleton_id: Bytes32,
    _pubkey: &[u8; 48],
) -> Bytes32 {
    // TODO: Implement currying of REGISTRATION_COIN_PUZZLE_HEX
    // with (pubkey, checkpoint_singleton_id) per REG-001
    Bytes32::default()
}
