//! Withdraw delay coin driver — time-locked collateral release.
//!
//! Created by the registration coin when a validator exits (WDC-004).
//! Holds collateral for WITHDRAW_DELAY_BLOCKS L1 blocks before releasing
//! to the specified destination.
//!
//! ## Puzzle Artifacts
//!
//! | Artifact | Path | Generated By |
//! |----------|------|-------------|
//! | CLVM hex | `puzzles/compiled/withdraw_delay_coin.hex` | `rue build -x puzzles/withdraw_delay_coin.rue` |
//! | Mod hash | `puzzles/compiled/withdraw_delay_coin.hash` | `rue build --hash puzzles/withdraw_delay_coin.rue` |
//!
//! ## Curried Parameters (set by registration coin at creation time)
//!
//! | Parameter | Type | Description |
//! |-----------|------|-------------|
//! | `DESTINATION` | Bytes32 | Puzzle hash where collateral goes after delay |
//! | `AMOUNT` | Int | Collateral amount in mojos |
//! | `WITHDRAW_DELAY_BLOCKS` | Int | L1 blocks to wait (default 24,000 ≈ 5 days) |
//!
//! ## Security Properties
//!
//! - No solution parameters — all behaviour curried in (SEC-008)
//! - Permissionless after delay — anyone can spend (WDC-007)
//! - Time lock enforced by Chia consensus, not CLVM (WDC-002)
//!
//! See [spec-withdraw-delay-coin.md](../../docs/resources/spec-withdraw-delay-coin.md)
//! for the full puzzle specification.

use chia_protocol::{Bytes32, SpendBundle};

use crate::error::ConsensusResult;

/// Compiled CLVM hex for the withdraw delay coin puzzle.
/// Generated by `rue build -x puzzles/withdraw_delay_coin.rue`.
///
/// This is the UNCURRIED puzzle. Each instance is curried with
/// (DESTINATION, AMOUNT, WITHDRAW_DELAY_BLOCKS), producing a unique
/// puzzle hash that commits to the exact destination, amount, and delay.
///
/// The puzzle emits exactly two conditions:
/// 1. ASSERT_HEIGHT_RELATIVE(WITHDRAW_DELAY_BLOCKS) — time lock (WDC-002)
/// 2. CREATE_COIN(DESTINATION, AMOUNT) — fund release (WDC-003)
///
/// See [spec-withdraw-delay-coin.md](../../docs/resources/spec-withdraw-delay-coin.md).
pub const WITHDRAW_DELAY_COIN_PUZZLE_HEX: &str =
    include_str!("../../puzzles/compiled/withdraw_delay_coin.hex");

/// Tree hash of the uncurried withdraw delay coin puzzle.
/// Generated by `rue build --hash puzzles/withdraw_delay_coin.rue`.
///
/// This MOD_HASH is used by:
/// - Registration coin: `curry_tree_hash(MOD_HASH, dest, amount, delay)` → delay coin puzzle hash
/// - NetworkConfig: stored as `withdraw_delay_mod_hash`
///
/// See [spec-withdraw-delay-coin.md](../../docs/resources/spec-withdraw-delay-coin.md).
pub const WITHDRAW_DELAY_COIN_MOD_HASH_HEX: &str =
    include_str!("../../puzzles/compiled/withdraw_delay_coin.hash");

/// Default withdraw delay: 24,000 blocks ≈ 5 days at ~18s/block.
///
/// Calculation: 5 × 24 × 60 × 60 / 18 = 24,000
pub const DEFAULT_WITHDRAW_DELAY_BLOCKS: u64 = 24_000;

/// Compute the puzzle hash of a withdraw delay coin.
///
/// WDC-005: Used by the registration coin on-chain (via curry_tree_hash)
/// and by the driver off-chain to predict the delay coin's puzzle hash.
///
/// Formula: `curry_tree_hash(WITHDRAW_DELAY_MOD_HASH, [dest, amount, delay])`
///
/// See [spec-withdraw-delay-coin.md](../../docs/resources/spec-withdraw-delay-coin.md).
pub fn withdraw_delay_puzzle_hash(
    _mod_hash: Bytes32,
    _destination: Bytes32,
    _amount: u64,
    _delay_blocks: u64,
) -> Bytes32 {
    // TODO: Implement using clvm_utils::curry_tree_hash
    // Must match the on-chain curry_tree_hash in registration_coin.rue
    Bytes32::default()
}

/// Build a spend bundle to release collateral from a withdraw delay coin.
/// Returns SpendBundle — the caller broadcasts it (API-008).
///
/// WDC-005: This is the second step of two-phase collateral recovery:
///   1. `recover_collateral()` — creates the withdraw delay coin
///   2. [wait `withdraw_delay_blocks` L1 blocks]
///   3. `release_collateral()` — releases funds to destination
///
/// If the delay has not elapsed, the Chia node will reject the bundle
/// (ASSERT_HEIGHT_RELATIVE failure).
///
/// The bundle uses identity signature (no AGG_SIG conditions — WDC-007).
/// CLVM cost: ~2.4M units.
///
/// See [spec-withdraw-delay-coin.md](../../docs/resources/spec-withdraw-delay-coin.md).
pub fn release_collateral(
    _withdraw_delay_coin_id: Bytes32,
    _destination: Bytes32,
    _amount: u64,
) -> ConsensusResult<SpendBundle> {
    // TODO: Implement using chia-wallet-sdk SpendContext
    // 1. Load WITHDRAW_DELAY_COIN_PUZZLE_HEX
    // 2. Curry with (destination, amount, delay_blocks)
    // 3. Build CoinSpend with nil solution
    // 4. Return SpendBundle with identity signature
    todo!()
}
